dir: .
dirs:
  astrald: .portal/astrald
  astraldb: .portal/astrald
  tokens: .portal/tokens
  bin: .portal/bin
  apps: apps
node:
  log:
    level: 100
apphost:
  listen:
    - tcp:127.0.0.1:8645
    - unix:.portal/astrald/.apphost.sock
    - memu:apphostu
    - memb:apphostb
  workers: 32
  object_server:
    bind:
      - tcp:127.0.0.1:8644
ether:
  udp_port: 8833
tcp:
  listen_port: 1792
