#!/bin/bash

CURRENT_DIR=$(pwd)
SCRIPT_DIR=$(dirname "$0")

cd "$SCRIPT_DIR" || exit
ENABLE_PORTAL_APPHOST_LOG=true PLOG=100 go run -tags project ./cmd/portal "$@"
CODE=$?
cd "$CURRENT_DIR" || exit $CODE
exit $CODE
