#!/bin/bash

CURRENT_DIR=$(pwd)
SCRIPT_DIR=$(dirname "$0")

cd "$SCRIPT_DIR" || exit
#PLOG=100 go run ./cmd/portald "$@"
PORTALD_HOME=$(pwd) PLOG=100 go run -tags project ./cmd/portald "$@"
cd "$CURRENT_DIR" || exit
