#!/bin/bash

CURRENT_DIR=$(pwd)
SCRIPT_DIR=$(dirname "$0")

cd "$SCRIPT_DIR" || exit
unset ASTRALD_APPHOST_TOKEN
ENABLE_PORTAL_APPHOST_LOG=true \
PORTALD_HOME=$(pwd) \
PORTALD_CONFIG_PATH=./debug.portal.env.yml \
go run -tags debug ./cmd/portald "$@"
cd "$CURRENT_DIR" || exit
